import * as Koa from 'koa';
import * as Router from '@koa/router';
import { RegisterRoutes } from '../generated/routes';
import * as cors from '@koa/cors';
import koaBody from 'koa-body';

const app = new Koa();

const router = new Router();
RegisterRoutes(router); // RegisterRoutes generated by tsoa

app.use(cors());
app.use(koaBody());
app.use(router.routes());
app.use(router.allowedMethods());
app.listen(3000);
